
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $docs  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
